FROM python:3.6

COPY docker/requirements.txt .
COPY src/main /main

RUN apt-get update && apt-get install -y ffmpeg \
    libsm6 \
    libxext6

RUN python -m pip install --upgrade pip 
RUN pip install -r requirements.txt

WORKDIR /main

CMD ["uvicorn", "start:app", "--host", "0.0.0.0", "--port", "4343"]
